server:
  port: 80
spring:
  application:
    name: gateway-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: admin-service_router
          uri: lb://admin-service
          predicates:
            - Path=/admin/**
        - id: test_router
          uri: http://www.aliyun.com
          predicates:
            - Path=/product
    sentinel:
      transport:
        dashboard: sentinel-server:8858 # 使用sentinel dashboard点击创建限流规则; 需要手动复制到nacos进行持久化(TBD);
      datasource:
#        # 1. Use static file
#        ds1.file:
#          file: classpath:gw-flow.json
#          rule-type: gw_flow
#        ds2.file:
#          file: classpath:api-group.json
#          rule-type: gw_api_group
        # 2. Use nacos config server, 可以动态刷新
        # 使用nacos持久化sentinel配置时,需要导入sentinel-datasource-nacos依赖;
        ds1.nacos:
          server-addr: nacos-server:8848
          data-id: gw-flow
          rule-type: gw_flow
        ds2.nacos:
          server-addr: nacos-server:8848
          data-id: api-group
          rule-type: gw_api_group
